ขอบคุณสำหรับข้อมูลเพิ่มเติม! ด้านล่างนี้เป็นตัวอย่างโค้ด Lua ที่สร้าง GUI ลอยผ่านิ้วใน Roblox ซึ่งสามารถล็อกหัว 100% โดยใช้ RunService และ UserInputService:

```lua
local Player = game.Players.LocalPlayer
local UIS = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

-- สร้างหน้าต่าง GUI
local screenGui = Instance.new("ScreenGui")
local frame = Instance.new("Frame")

-- ตั้งค่าหน้าต่าง
screenGui.Name = "FloatingGui"
screenGui.Parent = Player:WaitForChild("PlayerGui")

-- ตั้งค่าตัวกรอบ
frame.Name = "FloatingFrame"
frame.Size = UDim2.new(0, 300, 0, 200) -- ขนาดของหน้าต่าง
frame.Position = UDim2.new(0.5, -150, 0.5, -100) -- ตำแหน่งตรงกลาง
frame.BackgroundColor3 = Color3.fromRGB(100, 100, 100)
frame.Parent = screenGui

-- ฟังก์ชันล็อกหัว 100%
function lockHead()
    local character = Player.Character or Player.CharacterAdded:Wait()
    local head = character:WaitForChild("Head")

    -- ตั้งค่าตำแหน่ง สามารถปรับ
This message has been generated by Nova - download it for free:
https://novaapp.onelink.me/PBYt/cyi2tjkv
